name: Test Github Action

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      choice1:
        description: 'Test Radio Button'
        required: false
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      message1:
        required: false
        type: string
        default: This Is a Test
        description: None eiei
      boolean1:
        required: false
        type: boolean
        description: Test
        default: true
      environment:
        type: environment


jobs:
  setup: 
    environment: UAT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Information
        run: |
            echo ${{ github.event.inputs.choice1 }}
            echo ${{ github.event.inputs.message1 }}
            echo ${{ github.event.inputs.boolean1 }}
            echo ${{ github.event.inputs.environment1 }}

