name: Test Github Action
run-name: Manual ${{ inputs.deploy_target }} by @${{ github.actor }} for ${{ github.sha }}

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      choice1:
        description: 'Test Radio Button'
        required: false
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      commitHash:
        required: false
        type: string
        description: Git Reference
      boolean1:
        required: false
        type: boolean
        description: Test
        default: true
      environment:
        type: environment


jobs:
  setup: 
    environment: UAT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.event.inputs.commitHash }}
          fetch-depth: 0
      - name: Run Information
        run: |
            echo ${{ github.event.inputs.choice1 }}
            echo ${{ github.event.inputs.boolean1 }}
            echo ${{ github.event.inputs.commitHash }}
            echo ${{ github.event.inputs.environment1 }}

